### ISSUE TITLE
Add free text search

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/httpref#13]
**Is your feature request related to a problem? Please describe.**

There's a lot of information in this reference tool. It would be nice if we had the ability to search for terms that weren't only in titles.

**Describe the solution you'd like**

Perhaps something like this:

```
$ httpref --search auth

Authorisation
    This is a header that...

402
    This is returned when the request is unauthorised...
```

The search would be case insensitive (option?) and search though both headers and bodies.

Do we want to allow searches restricted to headers or status codes?

**Describe alternatives you've considered**

**Additional context**

**Comment by jan-carreras** [comment]
Would something like [bleve](https://blevesearch.com/) work for you? I may be interested in implementing it if it's OKay for you.

**Comment by dnnrly** [comment]
Sure, hack away.

**Comment by jesselang** [comment]
Hey @dnnrly, I'd like to pick this up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Would you be willing to assign it to me?

**Comment by dnnrly** [comment]
Hi @jesselang, thanks for getting involved.

**Comment by jan-carreras** [comment]
Sorry @dnnrly - life got in its way and I didn't finish the changes. @jesselang best of luck. This was my approach:

```go
package httpref

import (
	"github.com/blevesearch/bleve"
	"strconv"
)

type Search struct {
	index bleve.Index
	ref   References
}

func NewSearch(ref References) (*Search, error) {
	index, err := bleve.NewMemOnly(bleve.NewIndexMapping())
	if err != nil {
		return nil, err
	}

	for idx, p := range ref {
		if p.IsTitle {
			continue
		}

		err = index.Index(strconv.Itoa(idx), p.Description)
		if err != nil {
			return nil, err
		}
	}

	return &Search{index: index, ref: ref}, nil
}

func (s *Search) Search(text string) (References, error) {
	// TODO: Should be passing the size of results we want as an argument?
	search := bleve.NewSearchRequestOptions(bleve.NewMatchQuery(text), 100, 0, false)
	searchResults, err := s.index.Search(search)
	if err != nil {
		return nil, err
	}

	refs := make(References, 0, searchResults.Size())
	for _, result := range searchResults.Hits {
		id, err := strconv.Atoi(result.ID)
		if err != nil {
			return nil, err
		}
		if ref, found := s.ref.ByIndex(id); found {
			refs = append(refs, ref)
		}
	}

	return refs, nil
}
```

and could be used like:

```go
results := append(Statuses, Headers...)
	results = append(results, Methods...)
	results = append(results, RegisteredPorts...)
	results = append(results, WellKnownPorts...)

	search, err := NewSearch(results)
	if err != nil {
		t.Fatal(err)
	}

	refs, err := search.Search("port numbers")
	if err != nil {
		t.Fatal(err)
	}

	for _, ref := range refs {
		fmt.Println(ref.Describe(200))
	}
```

Not that you need to use any of if, but if it inspires you feel free to use the code.

**Comment by jesselang** [comment]
I didn't mean to steal your thunder, @jan-carreras. I did get a full text search working using the strings package. There's a bit of massaging to do yet, but I figured I'd start simple and look at indexing if the amount of content makes the search too slow.

**Comment by dnnrly** [comment]
Starting simple works for me! I saw your fork and definitely along the lines I was thinking. I look forward to your PR.

**Comment by dnnrly** [comment]
Hey @jesselang, how are you getting on with this. I'm really interested to see this contribution!

**Comment by jesselang** [comment]
Implement is done. Just need to get the feature into the docs.

**Comment by dnnrly** [comment]
Cool. Have you added an acceptance test?

**Comment by jesselang** [comment]
I added a test. Nothing fancy. Feel free to mention specific cases you'd like covered.
