### ISSUE TITLE
InRange returns incorrect registered ports

### ISSUE THREAD

**Issue by jan-carreras** [dnnrly/httpref#16]
**Describe the bug**

Some range registered ports are returned incorrectly

**To Reproduce**

```
make build
./httpref ports 16404
16384-16403
[... redacted ...]
```

**Expected behavior**

The range returned should include the port requested. Like so:

```
./httpref ports 16404
16403-16472
[... redacted ...]
```

**Desktop**

System Version: macOS 10.15.5 (19F101)  Kernel Version: Darwin 19.5.0

**Additional context**

The httpref.InRange function should change a condition from `if code >= parts[0] || code <= parts[len(parts)-1]` to `if code >= parts[0] && code <= parts[len(parts)-1]` to correctly identify the range.

I would like to submit a PR fixing this issue and improving the test case to ensure that the expected range is returned. Is that okay with you?

**Comment by dnnrly** [comment]
Yup, PRs are welcome!
