### ISSUE TITLE
Add HTTP 599 response

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/httpref#33]
**Is your feature request related to a problem? Please describe.**
I've seen 599 errors returned from Apache and it feels like it should be covered here.

**Describe the solution you'd like**
Concise description of 599 and a link to any further reading.

**Comment by Microctar** [comment]
Hello @dnnrly 
I can't even find the 599 status code in the httpd source code. 😔
link: https://github.com/apache/httpd/include/httpd.h

**Comment by dnnrly** [comment]
I know it's not exactly what I specified but there are some interesting hits in Github:

https://github.com/search?l=C&q=httpd+599&type=Code

**Comment by Microctar** [comment]
That's the non-standard http status code. We can also find 444 non-standard status code in [the nginx documentation](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return).
the following is the information of the standard http status code:
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by dnnrly** [comment]
I don't have a problem adding with non-standard codes. The tool is meant as a useful resource of information from the command line. Making a note that something isn't standard fits right in.

**Comment by Microctar** [comment]
I found some information related to the 599 status code:

https://github.com/tornadoweb/tornado/blob/master/tornado/httpclient.py
```python
695    * ``code`` - HTTP error integer error code, e.g. 404.  Error code 599 is
696      used when no HTTP response was received, e.g. for a timeout.
```

https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/utils.py
```python
271                    # we expect 599 for no connection,
```

https://github.com/serrynaimo/http-status-singlish#599-network-connect-timeout-error-unknown
rmaake1/httpstatuses#22

**Comment by selborsolrac** [comment]
Hello, I'd like to work on this issue for Hacktoberfest 2022!

I intend to add an http status `599` entry that looks like the following:
1. outputs one non-title element with input `httpref status 599` or `httpref 599`:
```
root@90b37c213622:/src# ./bin/httpref status 599
599
  Network Connect Timeout Error

The HTTP 599 Network Connect Timeout Error response status code signals a network connect timeout
behind the proxy to a client in front of the proxy.

This status code is not specified in any RFCs, but is used by some HTTP proxies to signal a network
connect timeout behind the proxy to a client in front of the proxy.

https://httpstatus.in/599/
```
```
root@90b37c213622:/src# ./bin/httpref 599  
599
  Network Connect Timeout Error

The HTTP 599 Network Connect Timeout Error response status code signals a network connect timeout
behind the proxy to a client in front of the proxy.

This status code is not specified in any RFCs, but is used by some HTTP proxies to signal a network
connect timeout behind the proxy to a client in front of the proxy.

https://httpstatus.in/599/
```
The title, summary, and description will be taken from https://httpstatus.in

I can submit a draft PR on 10/1. Let me know what you think!

**Comment by dnnrly** [comment]
As with all of my repos, feel free to submit a PR.
