### ISSUE TITLE
Colourised output

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/httpref#9]
**Is your feature request related to a problem? Please describe.**

Perhaps we could use a package like https://github.com/muesli/termenv to add colours to our output.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jkarelins** [comment]
**Describe alternatives you've considered**
Chalk is one of the most popular, ans easiest to use package: https://www.npmjs.com/package/chalk

**Comment by dnnrly** [comment]
Hi jkarelins, I'm afraid that won't work the way we need it to. As the project is written in Go we won't be able to consume that library.

BUT given this, if you're happy to contribute to the tool, then I'm very happy to guide you through the process!

**Comment by KhaledMam** [comment]
I'd like to contribute to the tool!
Can you please guide me through the process?

**Comment by dnnrly** [comment]
Of course! I'm going to assume you haven't contributed to open source on Github before so please feel free to correct me if you know this already.

1. The first step is to fork this repository.
2. Once you've made your first commit, you can raise a 'Draft Pull Request'
3. Once we get to that stage, I can add comments to the PR (Pull Request)

Do you have any experience with Go?

**Comment by KhaledMam** [comment]
Right now i am a complete novice but i am very excited to learn!
I'll get to work immediately.
Any further advice would be appreciated.

**Comment by dnnrly** [comment]
For now, just fork the repository:
https://help.github.com/en/github/getting-started-with-github/fork-a-repo

Then see if you can create a pull request:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

How much programming have you done before?

**Comment by KhaledMam** [comment]
I understand object oriented principles well and wrote your typical college projects (a CE student).

**Comment by dnnrly** [comment]
That's good. When you have raise the Pull Request, I'll be able to help you there more easily.

**Comment by KhaledMam** [comment]
Sorry for being a little late i had some minor technical difficulties that hindered me for a bit.
Mind my lack of knowledge but what is your idea of coloring the output?
what do you want it to look like?
And shouldn't i make some changes to the ccode before raising a pull request?

**Comment by dnnrly** [comment]
Don't worry about being late, this is supposed to be fun. :)

So if you haven't written Go before, spend a little time reading through some of the beginner tuturials.

After this, think about what you'd like the output to look like. To start off, perhaps you can change the colour of ALL of the text. Take a look at the documentation for `termenv` and see what you can come up with. If you commit a change that does then you have enough to raise a PR.

Don't worry, I don't want it to be perfect (or even working) to start with. I can talk you through what to do for the next steps.

**Comment by Mr-RamC** [comment]
Hi @dnnrly,

If this isn't already handled, Can I pick it up ?

**Comment by dnnrly** [comment]
No it's not, go for it. Do you have any ideas how you would tackle it?

**Comment by Mr-RamC** [comment]
As you suggested, we can go ahead with termenv.

**Comment by dnnrly** [comment]
I had an interesting thought about this the other day. Would it be easier to make an update to the paragraphical package? Perhaps adding an extra parameter or two for additional formatting?

**Comment by Mr-RamC** [comment]
Yup, Add support for colourised para's.

This can use the default colors, or we can have a global config of the color to use.

**Comment by dnnrly** [comment]
Cool, I look forward to seeing what you come up with!

**Comment by Mr-RamC** [comment]
@dnnrly I've described the first level changed to the paragraphical package at https://github.com/dnnrly/paragraphical/issues/4

Let me know what you think.

**Comment by KhaledMam** [comment]
Do as you want.

**Comment by rockey5520** [comment]
@dnnrly I find a good utility to colorize terminal output and remembered this issue.  linking the repo here for reference incase if it helps https://github.com/pterm/pterm
 :)

**Comment by dnnrly** [comment]
That's actually pretty neat @rockey5520! I can see how that could work nicely with interfaces. Hmmm....this might be an interesting distraction project.

**Comment by SharadNair7** [comment]
Hello @dnnrly,
Is this issue still up for grabs? If yes, I would like to work on this. I have experience with Python and C#. Would like to work with "Go" too.

Regards
Sharad

**Comment by dnnrly** [comment]
Sure, go for it. I don't typically reserve issues for people.
